/* Automatically generated nanopb constant definitions */
/* Generated by 0.4.1-dev */

#include "proto/updater.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(FVersion, FVersion, AUTO)


PB_BIND(FUpdateBinary, FUpdateBinary, AUTO)


PB_BIND(FChunxMessage, FChunxMessage, AUTO)



