/* Automatically generated nanopb header */
/* Generated by 0.4.1-dev */

#ifndef PB_PROTO_UPDATER_PB_H_INCLUDED
#define PB_PROTO_UPDATER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Version {
    pb_callback_t VersionString;
} Version;


/* Initializer values for message structs */
#define Version_init_default                     {{{NULL}, NULL}}
#define Version_init_zero                        {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Version_VersionString_tag                1

/* Struct field encoding specification for nanopb */
#define Version_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   VersionString,     1)
#define Version_CALLBACK pb_default_field_callback
#define Version_DEFAULT NULL

extern const pb_msgdesc_t Version_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Version_fields &Version_msg

/* Maximum encoded size of messages (where known) */
/* Version_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
